from __future__ import annotations

import argparse
import csv
import json
import math
import sys
from datetime import date, datetime
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd
import torch

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
from src.utils.artifacts import artifact_entry, write_json


DEFAULT_OUT_DIR = "review_samples/codex_fix_20062026"


def jsonable(value: Any, max_string: int = 2400) -> Any:
    if isinstance(value, dict):
        return {str(k): jsonable(v, max_string) for k, v in value.items()}
    if isinstance(value, list):
        return [jsonable(v, max_string) for v in value]
    if isinstance(value, tuple):
        return [jsonable(v, max_string) for v in value]
    if isinstance(value, np.ndarray):
        return [jsonable(v, max_string) for v in value.tolist()]
    if isinstance(value, (datetime, date, pd.Timestamp)):
        return value.isoformat()
    if isinstance(value, np.generic):
        return jsonable(value.item(), max_string)
    if isinstance(value, float) and (math.isnan(value) or math.isinf(value)):
        return None
    if value is pd.NA:
        return None
    if isinstance(value, str) and len(value) > max_string:
        return value[:max_string] + f"... [truncated {len(value) - max_string} chars]"
    return value


def write_jsonl(path: Path, rows: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        for row in rows:
            f.write(json.dumps(jsonable(row), ensure_ascii=False, sort_keys=True) + "\n")


def read_json_any(path: str) -> Any:
    p = Path(path)
    if not p.exists():
        return {}
    with p.open(encoding="utf-8") as f:
        return json.load(f)


def read_json(path: str) -> dict[str, Any]:
    data = read_json_any(path)
    return data if isinstance(data, dict) else {}


def compact_status_metrics(metrics: dict[str, Any]) -> dict[str, Any]:
    keep: dict[str, Any] = {}
    for key, value in metrics.items():
        if isinstance(value, (str, int, float, bool)) or value is None:
            keep[key] = value
        elif isinstance(value, dict) and len(value) <= 8:
            keep[key] = value
    return keep


def export_status_summary(out_dir: Path) -> Path:
    status_paths = sorted(Path("outputs/status").glob("*.status.json"))
    selected = [p for p in status_paths if p.name[:2].isdigit() and 1 <= int(p.name[:2]) <= 18]
    rows = []
    for path in selected:
        payload = read_json(str(path))
        rows.append(
            {
                "status_file": str(path).replace("\\", "/"),
                "step": payload.get("step"),
                "status": payload.get("status"),
                "next_step_allowed": payload.get("next_step_allowed"),
                "failures": payload.get("failures", []),
                "metrics_compact": compact_status_metrics(payload.get("metrics", {})),
            }
        )
    output = out_dir / "00_status_summary_01_18.json"
    write_json(output, {"rows": rows, "source_glob": "outputs/status/*.status.json"})
    return output


def export_source_index(out_dir: Path) -> Path:
    output = out_dir / "01_source_code_index.md"
    content = """# Source Code Index For `codex_fix_20062026` Review

Use this file as the code-review entrypoint. The sample files in this folder are small artifacts generated by these modules.

| Step | Main code paths | What to review |
|---|---|---|
| 06 | `src/llm/render_context.py`, `src/llm/generate_rationales.py` | Clean prompt context, no future labels, strict rationale JSON. |
| 07-08 | `src/judges/inferability_judge_independent_v3.py`, `src/judges/judge_debias_label_order_v3.py` | Independent judge prompt, reversed label order, debias consistency. |
| 09 | `src/judges/claim_level_grounding_v3.py` | Claim extraction, local NLI backend, no silent lexical PASS. |
| 10-11 | `src/reward/flow_dataset_v3.py`, `src/reward/train_flow_reward_v3.py`, `src/reward/evaluate_flow_vs_proxy_v3.py` | Masked multi-target flow dataset and proxy comparison. |
| 12-13 | `src/alignment/build_alignment_current_v3.py`, `src/alignment/train_current_v3.py` | RWSFT/DPO data contract and adapter training gate. |
| 14 | `src/eval/generate_test_predictions_v2.py`, `src/eval/backtest_daily_portfolio_v3.py` | Forecast-only prediction schema, test-only backtest, turnover cost. |
| 15 | `src/eval/build_counterfactual_current_v3.py`, `src/eval/evaluate_counterfactual_directional_v3.py` | Balanced counterfactual tasks and directional metrics. |
| 16 | `src/eval/run_current_ablation_suite_v3.py` | Real ablations; no `NOT_RUN` evidence rows. |
| 17-18 | `src/eval/build_current_v3_paper_tables.py`, `src/repro/currentdata_science_gate_v2.py` | Negative-result-safe tables and strict science gate. |
| Tests | `tests/test_claim_grounding_nli_loader.py`, `tests/test_step15_16_17_smoke_contracts.py` | Contracts for NLI, prediction, backtest, counterfactual, and gate behavior. |
"""
    output.write_text(content, encoding="utf-8")
    return output


def export_rationale_samples(out_dir: Path, n: int) -> Path:
    df = pd.read_parquet("data/rationales/parsed/current_clean_train_qwen3_4b_v3_fixed.parquet").head(n).copy()
    cols = [
        "sample_id",
        "split",
        "ticker",
        "event_timestamp",
        "candidate_id",
        "model_name",
        "prompt_hash",
        "run_id",
        "stage",
        "prompt",
        "raw_output",
        "parse_ok",
        "schema_ok",
        "parse_errors",
        "parsed_json",
    ]
    rows = df[[c for c in cols if c in df.columns]].to_dict("records")
    output = out_dir / "06_rationale_generation_samples.jsonl"
    write_jsonl(output, rows)
    return output


def export_inferability_samples(out_dir: Path, n: int) -> Path:
    df = pd.read_parquet("data/judges/independent_inferability_v3_1_debiased_small.parquet").head(n).copy()
    cols = [
        "sample_id",
        "candidate_id",
        "judge_model",
        "predicted_label",
        "true_label_probability",
        "true_label_probability_debiased",
        "p_strong_down",
        "p_mild_down",
        "p_neutral",
        "p_mild_up",
        "p_strong_up",
        "p_strong_down_debiased",
        "p_mild_down_debiased",
        "p_neutral_debiased",
        "p_mild_up_debiased",
        "p_strong_up_debiased",
        "argmax_consistency",
        "l1_probability_delta",
        "raw_judge_output",
        "raw_judge_output_reversed",
    ]
    output = out_dir / "07_08_inferability_debias_samples.jsonl"
    write_jsonl(output, df[[c for c in cols if c in df.columns]].to_dict("records"))
    return output


def export_grounding_samples(out_dir: Path, n: int) -> Path:
    df = pd.read_parquet("data/judges/claim_grounding_v3_1_small.parquet").head(n).copy()
    output = out_dir / "09_claim_grounding_nli_samples.jsonl"
    write_jsonl(output, df.to_dict("records"))
    return output


def export_flow_samples(out_dir: Path, n: int) -> Path:
    data = torch.load("data/reward/flow_v3_dataset.pt", map_location="cpu", weights_only=False)
    target_names = list(data.get("target_names", []))
    targets = np.asarray(data.get("target", []), dtype=float)
    masks = np.asarray(data.get("mask", []), dtype=float)
    sample_ids = list(data.get("sample_id", []))
    candidate_ids = list(data.get("candidate_id", []))
    splits = list(data.get("split", []))
    rows = []
    for idx in range(min(n, len(sample_ids))):
        rows.append(
            {
                "sample_id": sample_ids[idx],
                "candidate_id": candidate_ids[idx] if idx < len(candidate_ids) else None,
                "split": splits[idx] if idx < len(splits) else None,
                "target": {name: float(targets[idx, j]) for j, name in enumerate(target_names)},
                "mask": {name: float(masks[idx, j]) for j, name in enumerate(target_names)},
            }
        )
    output = out_dir / "10_flow_dataset_target_samples.json"
    write_json(
        output,
        {
            "source": "data/reward/flow_v3_dataset.pt",
            "rows_total": int(len(sample_ids)),
            "target_names": target_names,
            "metadata": data.get("metadata", {}),
            "samples": jsonable(rows),
        },
    )
    return output


def read_jsonl_head(path: str, n: int) -> list[dict[str, Any]]:
    rows = []
    with Path(path).open(encoding="utf-8") as f:
        for line in f:
            if len(rows) >= n:
                break
            if line.strip():
                rows.append(json.loads(line))
    return rows


def export_alignment_samples(out_dir: Path, n: int) -> list[Path]:
    outputs = []
    for source, name in [
        ("data/alignment/rwsft_current_v3_fixed.jsonl", "12_rwsft_alignment_samples.jsonl"),
        ("data/alignment/dpo_current_v3_fixed.jsonl", "12_dpo_alignment_pair_samples.jsonl"),
    ]:
        rows = read_jsonl_head(source, n)
        output = out_dir / name
        write_jsonl(output, rows)
        outputs.append(output)
    return outputs


def export_prediction_samples(out_dir: Path, per_action: int) -> Path:
    df = pd.read_parquet("outputs/predictions/current_v3_1_test_predictions.parquet").copy()
    rows = []
    for _, group in df.sort_values(["event_date", "ticker", "sample_id"]).groupby("action", dropna=False):
        rows.extend(group.head(per_action).to_dict("records"))
    output = out_dir / "14_prediction_forecast_samples.jsonl"
    write_jsonl(output, rows)
    return output


def export_backtest_sample(out_dir: Path, n: int) -> Path:
    df = pd.read_csv("outputs/tables/backtest_daily_returns_current_v3.csv").head(n).copy()
    output = out_dir / "14_backtest_daily_returns_sample.csv"
    output.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(output, index=False, quoting=csv.QUOTE_MINIMAL)
    return output


def export_counterfactual_samples(out_dir: Path, per_type: int) -> list[Path]:
    tasks = pd.read_parquet("data/counterfactual/current_cf_tasks_v3_1_small.parquet").copy()
    rows = []
    for _, group in tasks.sort_values(["counterfactual_type", "sample_id"]).groupby("counterfactual_type", dropna=False):
        rows.extend(group.head(per_type).to_dict("records"))
    task_output = out_dir / "15_counterfactual_task_samples.jsonl"
    write_jsonl(task_output, rows)

    fail_examples_raw = read_json_any("outputs/data_samples/counterfactual_fail_examples_current_v3.json")
    fail_examples = fail_examples_raw[: per_type * 4] if isinstance(fail_examples_raw, list) else fail_examples_raw
    fail_output = out_dir / "15_counterfactual_fail_examples.json"
    write_json(
        fail_output,
        {
            "source": "outputs/data_samples/counterfactual_fail_examples_current_v3.json",
            "examples": fail_examples,
        },
    )
    return [task_output, fail_output]


def export_table_and_gate_samples(out_dir: Path) -> list[Path]:
    outputs = []
    for source, name in [
        ("outputs/tables/ablation_current_v3.csv", "16_ablation_results.csv"),
        ("outputs/tables/current_v3_table_prediction.csv", "17_table_prediction.csv"),
        ("outputs/tables/current_v3_table_explanation.csv", "17_table_explanation.csv"),
        ("outputs/tables/current_v3_table_flow_reward.csv", "17_table_flow_reward.csv"),
        ("outputs/tables/current_v3_table_backtest.csv", "17_table_backtest.csv"),
        ("outputs/tables/current_v3_table_ablation.csv", "17_table_ablation.csv"),
    ]:
        df = pd.read_csv(source)
        output = out_dir / name
        df.to_csv(output, index=False)
        outputs.append(output)
    combined = {
        "claim_matrix": read_json("outputs/metrics/current_v3_claim_matrix.json"),
        "science_gate": read_json("outputs/repro/currentdata_science_gate_report_v2.json"),
    }
    output = out_dir / "18_claim_matrix_and_science_gate.json"
    write_json(output, combined)
    outputs.append(output)
    return outputs


def export_metrics_snapshot(out_dir: Path) -> Path:
    sources = [
        "outputs/metrics/claim_grounding_v3_1_small.json",
        "outputs/metrics/flow_v3_dataset_metrics.json",
        "outputs/metrics/flow_vs_proxy_v3_1_eval.json",
        "outputs/metrics/current_v3_1_test_predictions.json",
        "outputs/metrics/backtest_daily_portfolio_current_v3.json",
        "outputs/metrics/counterfactual_directional_current_v3.json",
        "outputs/metrics/ablation_current_v3.json",
    ]
    output = out_dir / "metrics_snapshot_current_v3_1.json"
    write_json(output, {path: read_json(path) for path in sources})
    return output


def export_readme(out_dir: Path, files: list[Path]) -> Path:
    listed_files = sorted({path.name for path in files} | {"README.md", "sample_manifest.json"})
    rows = "\n".join(f"- `{name}`" for name in listed_files)
    content = f"""# Codex Fix 2026-06-20 Review Samples

These files are small, GitHub-friendly samples from the `codex_fix_20062026` current-data V3.1 flow. They are intended for reviewing code/data contracts and content quality in ChatGPT UI without uploading raw datasets, model weights, or large checkpoints.

Recommended review order:

1. `01_source_code_index.md`
2. `06_rationale_generation_samples.jsonl`
3. `07_08_inferability_debias_samples.jsonl`
4. `09_claim_grounding_nli_samples.jsonl`
5. `10_flow_dataset_target_samples.json`
6. `12_rwsft_alignment_samples.jsonl` and `12_dpo_alignment_pair_samples.jsonl`
7. `14_prediction_forecast_samples.jsonl` and `14_backtest_daily_returns_sample.csv`
8. `15_counterfactual_task_samples.jsonl`
9. `16_ablation_results.csv`
10. `18_claim_matrix_and_science_gate.json`

Files:

{rows}
"""
    output = out_dir / "README.md"
    output.write_text(content, encoding="utf-8")
    return output


def export_manifest(out_dir: Path, files: list[Path]) -> Path:
    source_map = {
        "06_rationale_generation_samples.jsonl": "data/rationales/parsed/current_clean_train_qwen3_4b_v3_fixed.parquet",
        "07_08_inferability_debias_samples.jsonl": "data/judges/independent_inferability_v3_1_debiased_small.parquet",
        "09_claim_grounding_nli_samples.jsonl": "data/judges/claim_grounding_v3_1_small.parquet",
        "10_flow_dataset_target_samples.json": "data/reward/flow_v3_dataset.pt",
        "12_rwsft_alignment_samples.jsonl": "data/alignment/rwsft_current_v3_fixed.jsonl",
        "12_dpo_alignment_pair_samples.jsonl": "data/alignment/dpo_current_v3_fixed.jsonl",
        "14_prediction_forecast_samples.jsonl": "outputs/predictions/current_v3_1_test_predictions.parquet",
        "14_backtest_daily_returns_sample.csv": "outputs/tables/backtest_daily_returns_current_v3.csv",
        "15_counterfactual_task_samples.jsonl": "data/counterfactual/current_cf_tasks_v3_1_small.parquet",
        "15_counterfactual_fail_examples.json": "outputs/data_samples/counterfactual_fail_examples_current_v3.json",
        "16_ablation_results.csv": "outputs/tables/ablation_current_v3.csv",
        "18_claim_matrix_and_science_gate.json": "outputs/metrics/current_v3_claim_matrix.json; outputs/repro/currentdata_science_gate_report_v2.json",
    }
    output = out_dir / "sample_manifest.json"
    payload = {
        "producer": "src/repro/export_codex_fix_samples.py",
        "purpose": "Small samples for ChatGPT UI review of codex_fix_20062026 flow.",
        "sample_files": [artifact_entry(str(path), "CODEX_FIX_20062026_REVIEW_SAMPLES") for path in sorted(files)],
        "source_map": source_map,
    }
    write_json(output, payload)
    return output


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output-dir", default=DEFAULT_OUT_DIR)
    parser.add_argument("--sample-size", type=int, default=8)
    parser.add_argument("--prediction-per-action", type=int, default=3)
    parser.add_argument("--counterfactual-per-type", type=int, default=2)
    parser.add_argument("--backtest-days", type=int, default=20)
    args = parser.parse_args()

    out_dir = Path(args.output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    files: list[Path] = []
    files.append(export_status_summary(out_dir))
    files.append(export_source_index(out_dir))
    files.append(export_rationale_samples(out_dir, args.sample_size))
    files.append(export_inferability_samples(out_dir, args.sample_size))
    files.append(export_grounding_samples(out_dir, args.sample_size))
    files.append(export_flow_samples(out_dir, args.sample_size))
    files.extend(export_alignment_samples(out_dir, args.sample_size))
    files.append(export_prediction_samples(out_dir, args.prediction_per_action))
    files.append(export_backtest_sample(out_dir, args.backtest_days))
    files.extend(export_counterfactual_samples(out_dir, args.counterfactual_per_type))
    files.extend(export_table_and_gate_samples(out_dir))
    files.append(export_metrics_snapshot(out_dir))
    files.append(export_readme(out_dir, files))
    files.append(export_manifest(out_dir, files))

    print(json.dumps({"output_dir": str(out_dir), "files": [str(p) for p in files]}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
